let a = Number(prompt('Введите первое число:'))
let b = Number(prompt('Введите второе число:'))
console.log('a++ : ' + (a++))
console.log('b++ : ' + (b++))
console.log('a-- : ' + (a--))
console.log('b-- : ' + (b--))
console.log(String(a) + String(b))
console.log(String(b) + String(a))
console.log(a + String(b))
console.log(a + +(String(b)))
console.log(b + String(a))
console.log(b + +(String(a)))
console.log('Число a: ' + a)
console.log('Число b: ' + b)
console.log('Cумма a и b: '+ (a + b))
console.log('Разность a и b: '+ a - b)
console.log('Разность b и a: '+ (String(b) - a))
console.log('Произведение a и b: '+ a * b)
console.log('Частное от деления a на b: '+ a / b)
console.log('Частное от деления b на a: '+ b / a)
console.log('Остаток от деления a на b: '+ a % b)
console.log('Остаток от деления b на a: '+ b % a)
console.log('Возведение числа a в степень b: '+ a**b)
console.log('Возведение числа b в степень a: '+ b**a)
a += b
console.log('a = a + b : ' + (a))
b += a
console.log('b = b + a : ' + (b))