let a = Number(prompt('Введите первое число:'))
let b = Number(prompt('Введите второе число:'))
console.log('Число a: ' + a)
console.log('Число b: ' + b)
console.log('Cумма a и b: '+ (a + b))
console.log('Разность a и b: '+ a - b)
console.log('Произведение a и b: '+ a * b)
console.log('Частное от деления a на b: '+ a / b)
console.log('Частное от деления b на a: '+ b / a)
console.log('Остаток от деления a на b: '+ a % b)
console.log('Остаток от деления b на a: '+ b % a)
console.log('Возведение числа a в степень b: '+ a**b)
console.log('Возведение числа b в степень a: '+ b**a)